# Generated by Django 5.2.7 on 2025-11-07 08:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'Regular User'), ('admin', 'Administrator'), ('auditor', 'Auditor')], default='user', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('main', 'Main Account'), ('escrow', 'Escrow Account'), ('reserve', 'Reserve Account')], max_length=50)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('balance_hash', models.CharField(default='000000000000', editable=False, max_length=225)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_hash', models.CharField(editable=False, max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_account_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('fee', 'Fee'), ('refund', 'Refund')], max_length=50)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('entry_hash', models.CharField(editable=False, max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='erates.account')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parcel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disputed', 'Disputed'), ('transferred', 'Transferred'), ('archived', 'Archived')], default='active', max_length=20)),
                ('props', models.JSONField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcels',
            },
        ),
        migrations.CreateModel(
            name='ParcelHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('change_ts', models.DateTimeField(auto_now_add=True)),
                ('record_hash', models.CharField(editable=False, max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_changes_made', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='erates.parcel')),
            ],
            options={
                'db_table': 'parcel_history',
                'ordering': ['-change_ts'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('processor_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payment_hash', models.CharField(editable=False, max_length=64)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erates.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='users_usernam_b4c624_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner_user', 'status'], name='accounts_owner_u_ddfb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['who', '-created_at'], name='audit_logs_who_id_905fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-created_at'], name='ledger_entr_account_944a04_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['idempotency_key'], name='ledger_entr_idempot_5bfbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['owner_user', 'status'], name='parcels_owner_u_a11686_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['parcel_ref'], name='parcels_parcel__c66346_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelhistory',
            index=models.Index(fields=['parcel', '-change_ts'], name='parcel_hist_parcel__819554_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_status_db6b16_idx'),
        ),
    ]
