# Generated by Django 5.2.7 on 2025-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Payment deadline. If payment is not completed by this date, user becomes a defaulter.",
                null=True,
            ),
        ),
    ]
