# Generated by Django 5.2.7 on 2026-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erates', '0003_allow_null_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='county',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='sub_county',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='ward',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
