# Generated by Django 5.2.7 on 2026-09-11 15:41

import django.db.models.deletion
from django.db import migrations, models

ADD_PAYMENT_COLUMNS = """
ALTER TABLE payments ADD COLUMN IF NOT EXISTS parcel_id uuid NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_year integer NULL;
CREATE INDEX IF NOT EXISTS payments_parcel_id_fd9cd151 ON payments (parcel_id);
CREATE INDEX IF NOT EXISTS payments_payment_year_c07b169d ON payments (payment_year);
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_parcel_id_fd9cd151_fk_parcels_parcel_id') THEN
        ALTER TABLE payments ADD CONSTRAINT payments_parcel_id_fd9cd151_fk_parcels_parcel_id
            FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('erates', '0006_rehash_history_and_audit_chains'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('receipt', models.CharField(blank=True, db_index=True, max_length=30)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpesa_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='land_use',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural'), ('institutional', 'Institutional'), ('mixed', 'Mixed Use')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='unimproved_site_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USV from the county valuation roll; blank means flat-rate by area', max_digits=20, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            # Some databases already have these columns from an unreleased 2025 migration
            database_operations=[migrations.RunSQL(ADD_PAYMENT_COLUMNS, migrations.RunSQL.noop)],
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='parcel',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erates.parcel'),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='payment_year',
                    field=models.IntegerField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel__isnull', False), ('payment_year__isnull', False)), fields=('parcel', 'payment_year'), name='one_rate_bill_per_parcel_year'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to='erates.payment'),
        ),
    ]
