# Generated by Django 5.2.7 on 2026-09-12 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erates', '0011_county_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelDeletionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why this parcel should go; shown to the platform owner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='erates.parcel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcel_deletions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel_deletion_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='parcel_dele_status_d8a55f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'pending')), fields=('parcel',), name='one_open_deletion_request_per_parcel')],
            },
        ),
    ]
