# Generated by Django 5.2.7 on 2026-09-15 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erates', '0013_drop_orphan_locality_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('bands', models.JSONField(help_text='Flat area rates, ascending: [{"max_ha": "0.1", "amount": "2560"}]')),
                ('top_amount', models.DecimalField(decimal_places=2, help_text='Flat rate above the largest band', max_digits=12)),
                ('usv_rate_percent', models.DecimalField(decimal_places=4, help_text='Percent of unimproved site value, for parcels that have one', max_digits=7)),
                ('deadline', models.DateTimeField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_schedules', to='erates.county')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_schedules_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rate_schedules',
                'ordering': ['county__name', '-year'],
                'constraints': [models.UniqueConstraint(fields=('county', 'year'), name='one_rate_schedule_per_county_year')],
            },
        ),
    ]
