# Generated by Django 5.2.7 on 2026-09-15 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erates', '0016_kenya_counties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_reference', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('years', models.JSONField(blank=True, default=list)),
                ('sub_counties', models.JSONField(blank=True, default=list)),
                ('wards', models.JSONField(blank=True, default=list)),
                ('land_uses', models.JSONField(blank=True, default=list)),
                ('parcel_refs', models.JSONField(blank=True, default=list)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('bills_affected', models.IntegerField(default=0)),
                ('amount_waived', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waivers', to='erates.county')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waivers_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waivers_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
