# Generated by Django 5.2.7 on 2026-09-15 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erates', '0017_waivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('claim_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiver_claims', to='erates.parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiver_claims', to=settings.AUTH_USER_MODEL)),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='erates.waiver')),
            ],
            options={
                'db_table': 'waiver_claims',
                'constraints': [models.UniqueConstraint(fields=('waiver', 'parcel'), name='one_claim_per_waiver_parcel')],
            },
        ),
    ]
